# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5b463daec68d3cf83911bda7da3df41b418d96ba73b15e6b896bac7f45465b61a268f3d22c0f603ce402fcf98e0dbddbc9ff287c6b1df949933111e037318fc

test:
  secret_key_base: 2d3f7736f71420a233bcc22096df41491cb971fdac3b5cbdbe0f25e2ffc7ae75d17ba3c147ab2e6c94e1e808667241a0cc2c2afbc8ed0c842d49c59f5d65a438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
